//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 05:46:59 PM WIB 
//


package id.co.danamon.dbank.servicename.domain.dto.common.esb.header;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CIMB_StatusRqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cimbStatusRqUID",
    "cimbStatusCode",
    "cimbStatusDesc",
    "cimbSeverity"
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CIMBProviderRespStatus  {

    @XmlElement(name = "CIMB_StatusRqUID")
    protected String cimbStatusRqUID;
    @XmlElement(name = "CIMB_StatusCode")
    protected String cimbStatusCode;
    @XmlElement(name = "CIMB_StatusDesc")
    protected String cimbStatusDesc;
    @XmlElement(name = "CIMB_Severity")
    protected String cimbSeverity;

}
