//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 05:45:30 PM WIB 
//


package id.co.danamon.dbank.servicename.domain.dto.common.esb.header;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CIMB_ProviderRqUID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CIMB_ProviderSystemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "cimbProviderRqUID",
        "cimbProviderSystemCode",
        "cimbProviderAuthDetail",
        "cimbProviderRespDateTime",
        "cimbProviderRespStatusList"
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CIMBProvider  {

    @XmlElement(name = "CIMB_ProviderRqUID")
    protected String cimbProviderRqUID;
    @XmlElement(name = "CIMB_ProviderSystemCode")
    protected String cimbProviderSystemCode;

    @XmlElement(name = "CIMB_ProviderAuthDetail")
    protected CIMBProviderAuthDetail cimbProviderAuthDetail;
    @XmlElement(name = "CIMB_ProviderRespDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cimbProviderRespDateTime;
    @XmlElement(name = "CIMB_ProviderRespStatusList")
    protected CIMBProviderRespStatusList cimbProviderRespStatusList;


}
