//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 05:46:59 PM WIB 
//


package id.co.danamon.dbank.servicename.domain.dto.common.esb.header.response;

import id.co.danamon.dbank.servicename.domain.dto.common.esb.header.CIMBPaginationList;
import id.co.danamon.dbank.servicename.domain.dto.common.esb.header.CIMBProviderList;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CIMB_ConsumerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_ConsumerPasswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_ServiceVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="CIMB_SrcSystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_ProviderList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CIMB_Provider">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CIMB_ProviderRqUID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CIMB_ProviderSystemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CIMB_ProviderAuthDetail">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CIMB_ProviderUserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CIMB_ProviderUserPasswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CIMB_ProviderRespDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="CIMB_ProviderRespStatusList">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CIMB_ProviderRespStatus">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="CIMB_StatusRqUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="CIMB_StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="CIMB_StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="CIMB_Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CIMB_SrcCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_ServicePagingFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CIMB_PaginationList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CIMB_Pagination">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CIMB_ProviderPaginationKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "cimbConsumerId",
        "cimbConsumerPasswd",
        "cimbServiceName",
        "cimbServiceVersion",
        "cimbSrcSystem",
        "cimbProviderList",
        "cimbSrcCountryCode",
        "cimbServicePagingFlag",
        "cimbPaginationList"
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CIMBHeaderRs  {

    @XmlElement(name = "CIMB_ConsumerId", required = true)
    protected String cimbConsumerId;
    @XmlElement(name = "CIMB_ConsumerPasswd", required = true)
    protected String cimbConsumerPasswd;
    @XmlElement(name = "CIMB_ServiceName", required = true)
    protected String cimbServiceName;
    @XmlElement(name = "CIMB_ServiceVersion")
    protected float cimbServiceVersion;
    @XmlElement(name = "CIMB_SrcSystem", required = true)
    protected String cimbSrcSystem;
    @XmlElement(name = "CIMB_ProviderList", required = true)
    protected CIMBProviderList cimbProviderList;
    @XmlElement(name = "CIMB_SrcCountryCode", required = true)
    protected String cimbSrcCountryCode;
    @XmlElement(name = "CIMB_ServicePagingFlag", required = true)
    protected String cimbServicePagingFlag;
    @XmlElement(name = "CIMB_PaginationList", required = true)
    protected CIMBPaginationList cimbPaginationList;

}
